sudo: required

language: go

services:
  - docker

go:
  - "1.21.0"

branches:
  only:
  - master
  - coveralls


before_install:
  - go install github.com/mattn/goveralls@latest
  - docker network create ranger-env


env:
  - DOCKER_COMPOSE_VERSION=1.22.0 GO111MODULE=on

script:
  - set -e
  - go fmt ./...
  - PATH=$PATH:$HOME/.local/bin bash ./scripts/integration.sh
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
