# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Ranger
      run: |
        docker network create ranger-env
        git clone https://github.com/kadensungbincho/apache-ranger-docker-poc.git
        cd apache-ranger-docker-poc/docker-composes/ranger
        docker-compose up -d

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: |
        go install github.com/mattn/goveralls@latest
        go test -v client/
        $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
